# Generated by Django 3.2.7 on 2022-01-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('AnnotationId', models.AutoField(primary_key=True, serialize=False)),
                ('Document', models.CharField(max_length=10000)),
                ('Annotation', models.CharField(max_length=1000)),
            ],
        ),
    ]
