# Generated by Django 3.2.11 on 2022-01-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('AnnotationId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
